### ISSUE TITLE
[1.15.2] Supremacy of Diamond and more

### ISSUE THREAD

**Issue by Mikeliro** [kwpugh/easy_steel#7]
- Steel to tungsten paxel can mine obsidian
- All the hammers can mine obsidian
- If you mine a block of land for example with a hammer and have an obsidian on the side it will be mined
-

**Comment by kwpugh** [comment]
Yep.  I'm still trying to figure this one out.  I need to figure out how to have the harvest level checked for each block.

**Comment by kwpugh** [comment]
Ok, I figured it out.  Now a basic choice.

I had given Steel and above material harvest level 3 (diamond).  This was prior to the re-balancing.  

I am going to drop all the material above iron to be the same harvest level as steel, so that diamond pickaxe is the only one with level 3.

What do you think?

**Comment by kwpugh** [comment]
Said another way, Flint will be Stone level harvest and Bronze thru Tungsten-carbide will be Iron harvest level.

**Comment by Mikeliro** [comment]
This is great
